AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for VPC'

Resources:
  clvpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '172.16.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      tags:
        - Key: 'Name'
          Value: 'clvpc'
        